CREATE TABLE MEMBER
(
    MEMBER_ID VARCHAR2(50),
    MEMBER_PWD VARCHAR2(200) NOT NULL,
    MEMBER_NAME VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(200),
    ADDRESS VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    UNIQUE(PHONE,EMAIL),PRIMARY KEY(MEMBER_ID)
);



CREATE TABLE MEMBER
(
    MEMBER_ID VARCHAR2(50),
    MEMBER_PWD VARCHAR2(200) NOT NULL,
    MEMBER_NAME VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(200),
    ADDRESS VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    GRADE VARCHAR2(5) DEFAULT 1,
    CUR_ROOM_CNT VARCHAR2(10) DEFAULT 0,
    MAX_ROOM_CNT VARCHAR2(10) DEFAULT 3,
    REPORT_CNT VARCHAR2(10) DEFAULT 0,
    POINT VARCHAR2(20) DEFAULT 0,
    LEAVE_MEM VARCHAR2(1) DEFAULT 0,
    CUR_TRADE_LIST VARCHAR2(200) DEFAULT NULL,
    TRADE_LIST VARCHAR2(200) DEFAULT NULL,
    LIKE_LIST VARCHAR2(200) DEFAULT NULL,
    UNIQUE(PHONE,EMAIL),PRIMARY KEY(MEMBER_ID)
);


------------------------------------------------------------------------------------------


CREATE SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_BOARD_NO;




DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_ID VARCHAR2(50),
    MEMBER_PWD VARCHAR2(200) NOT NULL,
    MEMBER_NAME VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(200) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    GRADE VARCHAR2(100) DEFAULT 1,
    CUR_ROOM_CNT VARCHAR2(10) DEFAULT 0,
    MAX_ROOM_CNT VARCHAR2(10) DEFAULT 3,
    REPORT_CNT VARCHAR2(10) DEFAULT 0,
    POINT VARCHAR2(20) DEFAULT 0,
    LEAVE_MEM VARCHAR2(1) DEFAULT 0,
    CUR_TRADE_LIST VARCHAR2(200) DEFAULT NULL,
    TRADE_LIST VARCHAR2(200) DEFAULT NULL,
    LIKE_LIST VARCHAR2(200) DEFAULT NULL,
    MEMBER_PICTURE VARCHAR2(200) DEFAULT NULL,
    UNIQUE(EMAIL),PRIMARY KEY(MEMBER_ID)
);

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원비밀번호(단방향)';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '회원닉네임';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호(양방향)';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소(양방향)';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일(양방향)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입날짜';
COMMENT ON COLUMN MEMBER.GRADE IS '회원등급';
COMMENT ON COLUMN MEMBER.CUR_ROOM_CNT IS '현재개설한방갯수';
COMMENT ON COLUMN MEMBER.MAX_ROOM_CNT IS '개설가능한방갯수';
COMMENT ON COLUMN MEMBER.REPORT_CNT IS '신고당한횟수';
COMMENT ON COLUMN MEMBER.POINT IS '포인트수치';
COMMENT ON COLUMN MEMBER.LEAVE_MEM IS '회원탈퇴여부 Boolean';
COMMENT ON COLUMN MEMBER.CUR_TRADE_LIST IS '거래중인게시글리스트';
COMMENT ON COLUMN MEMBER.TRADE_LIST IS '과거거래내역리스트';
COMMENT ON COLUMN MEMBER.LIKE_LIST IS '추천게시글리스트';
COMMENT ON COLUMN MEMBER.MEMBER_PICTURE IS '회원사진';

------------------------------------------------------------------------------------------

DROP TABLE BOARD;

CREATE TABLE BOARD(
    BOARD_ID NUMBER,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    WRITER_ID VARCHAR2(50),
    CONTENT VARCHAR2(1000),
    ENROLL_DATE TIMESTAMP DEFAULT SYSDATE,
    HIT NUMBER DEFAULT 0,
    FILES VARCHAR2(2000) DEFAULT NULL,
    PRODUCT_CATEGORI VARCHAR2(50),
    PRODUCT_NAME VARCHAR2(50),
    DELIVERY_TIME TIMESTAMP DEFAULT (SYSDATE + 3*24/24),
    TRADE_AREA VARCHAR2(200),
    MAX_MEMS VARCHAR2(50) DEFAULT 3,
    CUR_MEMS_LIST VARCHAR2(200) DEFAULT NULL,
    LIMIT_TRADE_TIME TIMESTAMP DEFAULT (SYSDATE + 2/24),
    TRADE_STAGE VARCHAR2(10) DEFAULT 1,
    TRADE_START VARCHAR2(10) DEFAULT 0,
    POPULAR_BOARD VARCHAR2(10) DEFAULT 0,
    PRODUCT_PRICE NUMBER(20) NOT NULL,
    OWN_STATUS VARCHAR2(30) NOT NULL,
    TRADE_KIND VARCHAR2(30) NOT NULL,
    PRODUCT_URL VARCHAR2(50) DEFAULT NULL,
    PRIMARY KEY(BOARD_ID)
);

INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE1','ADMIN','HIHIHIHIHIH','bs.jpg','특가','오! 그래놀라','강동구 상일동','20000','구매예정','직거래');



COMMENT ON COLUMN BOARD.BOARD_ID IS '게시글아이디';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.WRITER_ID IS '게시글작성자아이디';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.ENROLL_DATE IS '게시글등록날짜';
COMMENT ON COLUMN BOARD.HIT IS '조회수';
COMMENT ON COLUMN BOARD.FILES IS '파일첨부(파일명.확장자)';
COMMENT ON COLUMN BOARD.PRODUCT_CATEGORI IS '제품 카테고리';
COMMENT ON COLUMN BOARD.PRODUCT_NAME IS '제품 이름';
COMMENT ON COLUMN BOARD.DELIVERY_TIME IS '배송 예정 시간';
COMMENT ON COLUMN BOARD.TRADE_AREA IS '거래 지역';
COMMENT ON COLUMN BOARD.MAX_MEMS IS '최대 N빵 회원 수(방장이 실시간으로 변경 가능)';
COMMENT ON COLUMN BOARD.CUR_MEMS_LIST IS '현재 회원 리스트';
COMMENT ON COLUMN BOARD.LIMIT_TRADE_TIME IS '거래 예정 시간';
COMMENT ON COLUMN BOARD.TRADE_STAGE IS '거래 진행 단계';
COMMENT ON COLUMN BOARD.TRADE_START IS '거래 활성화 여부 Boolean';
COMMENT ON COLUMN BOARD.POPULAR_BOARD IS '인기 게시물 활성화 여부 Boolean';
COMMENT ON COLUMN BOARD.PRODUCT_PRICE IS '제품의가격';
COMMENT ON COLUMN BOARD.OWN_STATUS IS '제품보유상태';
COMMENT ON COLUMN BOARD.TRADE_KIND IS '거래 종류';
COMMENT ON COLUMN BOARD.PRODUCT_URL IS '제품 URL';
COMMIT;



    DROP TABLE NOTICE;

       CREATE TABLE NOTICE(
        NOTICE_NO NUMBER PRIMARY KEY,
        NOTICE_TITLE VARCHAR2(100) NOT NULL,
        NOTICE_WRITER VARCHAR2(15) NOT NULL,
        NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
        NOTICE_DATE DATE DEFAULT SYSDATE,
        FILEPATH VARCHAR2(300),
        STATUS VARCHAR2(1) DEFAULT 'Y'
    );
    
    INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL,'공지사항테스트','admin','공지사항테스트입니다',default,null,default);


   CREATE SEQUENCE SEQ_NOTICE_NO;







------------------------------------------------------------------------------------------

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
  COM_ID NUMBER,
  CBOARD_ID NUMBER NOT NULL,
  "COMMENT" VARCHAR2(1000),
  CWRITER_ID VARCHAR2(50) DEFAULT NULL,
  CENROLL_DATE TIMESTAMP DEFAULT SYSDATE,
  SECRET NUMBER DEFAULT 0,
  PRIMARY KEY (COM_ID)
);

COMMENT ON COLUMN "COMMENT".COM_ID IS '댓글 아이디';
COMMENT ON COLUMN "COMMENT".CBOARD_ID IS '댓글 달린 게시물 아이디';
COMMENT ON COLUMN "COMMENT"."COMMENT" IS '댓글 내용';
COMMENT ON COLUMN "COMMENT".CWRITER_ID IS '댓글 작성자 아이디';
COMMENT ON COLUMN "COMMENT".CENROLL_DATE IS '댓글 작성 날짜';
COMMENT ON COLUMN "COMMENT".SECRET IS '비밀 댓글 여부 Boolean';
COMMIT;

------------------------------------------------------------------------------------------

SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM "COMMENT";








-------------------------------

DESC MEMBER;
SELECT * FROM MEMBER;
SELECT * FROM BOARD;
DELETE FROM BOARD;
COMMIT;

<<<<<<< HEAD

--멤버 테스트용 계정
INSERT INTO MEMBER VALUES('admin','admin','관리자','관리자','01012345678','서울시 서초구', 'admin@admin', sysdate, default,
default, default, default, default, default, default, default, default);
COMMIT;
SELECT * FROM MEMBER where member_id='admin' and member_pwd='admin';
=======
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE1','user1','content1','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE2','user2','content2','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE3','user3','content3','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE4','user4','content4','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE5','user5','content5','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE6','user6','content6','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE7','user7','content7','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE8','user8','content8','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE9','user9','content9','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE10','user10','content10','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE11','user11','content11','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE12','user12','content12','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE13','user13','content13','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE14','user14','content14','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE15','user15','content15','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE16','user16','content16','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE17','user17','content17','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE18','user18','content18','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE19','user19','content19','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE20','user20','content20','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE21','user21','content21','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE22','user22','content22','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE23','user23','content23','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE24','user24','content24','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE25','user25','content25','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE26','user26','content26','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE27','user27','content27','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE28','user28','content28','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE29','user29','content29','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE30','user30','content30','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE31','user31','content31','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE32','user32','content32','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE33','user33','content33','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE34','user34','content34','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE35','user35','content35','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE36','user36','content36','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE37','user37','content37','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE38','user38','content38','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE39','user39','content39','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE40','user40','content40','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE41','user41','content41','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE42','user42','content42','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE43','user43','content43','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE44','user44','content44','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE45','user45','content45','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE46','user46','content46','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE47','user47','content47','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE48','user48','content48','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE49','user49','content49','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE50','user50','content50','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE51','user51','content51','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE52','user52','content52','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE53','user53','content53','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE54','user54','content54','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE55','user55','content55','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE56','user56','content56','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE57','user57','content57','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE58','user58','content58','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE59','user59','content59','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE60','user60','content60','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE61','user61','content61','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE62','user62','content62','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE63','user63','content63','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE64','user64','content64','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE65','user65','content65','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE66','user66','content66','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE67','user67','content67','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE68','user68','content68','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE69','user69','content69','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE70','user70','content70','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE71','user71','content71','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE72','user72','content72','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE73','user73','content73','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE74','user74','content74','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE75','user75','content75','3.jpg','특가','페이스핏','강동구 상일동','30000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE76','user76','content76','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE77','user77','content77','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE78','user78','content78','1.jpg','특가','오! 그래놀라','강동구 상일동','10000','구매예정','직거래');
INSERT INTO BOARD(BOARD_ID,BOARD_TITLE,WRITER_ID,CONTENT,FILES,PRODUCT_CATEGORI,PRODUCT_NAME,TRADE_AREA,PRODUCT_PRICE,OWN_STATUS,TRADE_KIND) VALUES(SEQ_BOARD_NO.NEXTVAL,'NOTITLE79','user79','content79','2.jpg','특가','스파클','강동구 상일동','20000','구매예정','직거래');



commit;



INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('admin','0000','admin','ADMIN','01082308775','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user1','user1','name1','nickname1','0109474885','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user2','user2','name2','nickname2','01058631024','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user3','user3','name3','nickname3','01065003651','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user4','user4','name4','nickname4','01033387961','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user5','user5','name5','nickname5','01081535959','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user6','user6','name6','nickname6','0102926961','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user7','user7','name7','nickname7','01038954722','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user8','user8','name8','nickname8','01062786570','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user9','user9','name9','nickname9','01068231627','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user10','user10','name10','nickname10','01033102491','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user11','user11','name11','nickname11','01045201900','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user12','user12','name12','nickname12','01072938452','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user13','user13','name13','nickname13','01098573296','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user14','user14','name14','nickname14','010753182','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user15','user15','name15','nickname15','01074846351','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user16','user16','name16','nickname16','01043226635','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user17','user17','name17','nickname17','01024179842','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user18','user18','name18','nickname18','01012155855','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user19','user19','name19','nickname19','01084900895','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user20','user20','name20','nickname20','01065149179','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user21','user21','name21','nickname21','01096349387','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user22','user22','name22','nickname22','0103569053','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user23','user23','name23','nickname23','01068172093','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user24','user24','name24','nickname24','0101520811','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user25','user25','name25','nickname25','01013785577','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user26','user26','name26','nickname26','01018905568','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user27','user27','name27','nickname27','01021512841','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user28','user28','name28','nickname28','01029105149','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user29','user29','name29','nickname29','01023689838','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user30','user30','name30','nickname30','01095308084','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user31','user31','name31','nickname31','01062823839','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user32','user32','name32','nickname32','01062460996','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user33','user33','name33','nickname33','01055717356','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user34','user34','name34','nickname34','01042478440','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user35','user35','name35','nickname35','01066106561','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user36','user36','name36','nickname36','01051299625','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user37','user37','name37','nickname37','01083499377','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user38','user38','name38','nickname38','01047582274','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user39','user39','name39','nickname39','01036023677','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user40','user40','name40','nickname40','01049861544','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user41','user41','name41','nickname41','01023611761','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user42','user42','name42','nickname42','01030002540','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user43','user43','name43','nickname43','01032743363','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user44','user44','name44','nickname44','01084609163','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user45','user45','name45','nickname45','01065060290','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user46','user46','name46','nickname46','01066725778','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user47','user47','name47','nickname47','01078430630','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user48','user48','name48','nickname48','01035666522','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user49','user49','name49','nickname49','01075539033','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user50','user50','name50','nickname50','01071880930','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user51','user51','name51','nickname51','01088642807','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user52','user52','name52','nickname52','01041050991','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user53','user53','name53','nickname53','01061728712','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user54','user54','name54','nickname54','01029819747','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user55','user55','name55','nickname55','01057728819','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user56','user56','name56','nickname56','0101370625','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user57','user57','name57','nickname57','01021789584','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user58','user58','name58','nickname58','01025850173','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user59','user59','name59','nickname59','0106489167','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user60','user60','name60','nickname60','01072209932','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user61','user61','name61','nickname61','0109817163','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user62','user62','name62','nickname62','01038221377','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user63','user63','name63','nickname63','01069132379','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user64','user64','name64','nickname64','0105310108','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user65','user65','name65','nickname65','01069162460','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user66','user66','name66','nickname66','01069779399','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user67','user67','name67','nickname67','01011885773','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user68','user68','name68','nickname68','0103392194','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user69','user69','name69','nickname69','01067498662','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user70','user70','name70','nickname70','01011111871','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user71','user71','name71','nickname71','01045486547','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user72','user72','name72','nickname72','01097268796','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user73','user73','name73','nickname73','01038156099','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user74','user74','name74','nickname74','01077017368','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user75','user75','name75','nickname75','01067852349','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user76','user76','name76','nickname76','01026920285','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user77','user77','name77','nickname77','01072272912','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user78','user78','name78','nickname78','01029287776','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);
INSERT INTO MEMBER(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,NICKNAME,PHONE,ADDRESS,EMAIL,ENROLL_DATE) VALUES ('user79','user79','name79','nickname79','01089906064','서울시 강동구 상일동','rain46688@gmail.com',SYSDATE);

commit;








>>>>>>> df68beb6f66eb0769ed4c782c76fdc95dbec6bc7
